### ISSUE TITLE
Alpha/Beta version compare 

### ISSUE THREAD

**Issue by evgeniynickolaev** [zafarkhaja/jsemver#30]
Hello!
It seems the version comparison is diverted with the SemVer Specification

```
       @Test
        public void preReleaseShouldHaveLowerPrecedenceThanAssociatedNormal() {
            Version v1 = Version.valueOf("1.3.7");
            Version v2 = Version.valueOf("1.3.7-alpha");
            assertTrue(0 < v1.compareTo(v2));
            assertTrue(0 > v2.compareTo(v1));
        }
```

So 1.3.7 < 1.3.7-alpha.

But according to the SemVer spec:

http://semver.org/

```

When major, minor, and patch are equal,
a pre-release version has lower precedence than a normal version.
Example: 1.0.0-alpha < 1.0.0.
```

It should be visa versa.

**Comment by zafarkhaja** [comment]
Hi, thank you for taking the time to contribute.

As far as I'm concerned every thing is correct here. According to the documentation `compareTo` returns

> a negative integer, zero, or a positive integer as this object is less than, equal to, or greater than the specified object.

So
```
v1 > v2 => 0 < v1.compareTo(v2) // positive
v2 < v1 => 0 > v2.compareTo(v1) // negative
```

Let me know if you need any more clarifications.

**Comment by evgeniynickolaev** [comment]
Yes technically it is correct.
But you consider 1.3.7 < 1.3.7-alpha, this is conflicts to the SemVer specifications as long as pre-release versions are considering older than release versions.

**Comment by evgeniynickolaev** [comment]
Oh, I am sorry, I was confused somewhere in my tests using your awesome library.
Thanks!
