### ISSUE TITLE
Support for Version Match Expressions

### ISSUE THREAD

**Issue by buko** [zafarkhaja/jsemver#41]
Between jsemver and [semver.java](https://github.com/jknack/semver.java) we have all the functionality we need. It would be great if we could combine them. What's nice about semver.java is the match expression language. You can express conditons like ">=1.0.0" and then test to see if a given Version "matches" this condition.

**Comment by loganvolkers** [comment]
Try this library, it seems to be more full featured and might help you: https://github.com/vdurmont/semver4j

**Comment by zafarkhaja** [comment]
Hello @buko! Sorry it took me this long to get back to you.

If it's still relevant to you, could you please take a look at [SemVer Expressions API (Ranges)](https://github.com/zafarkhaja/jsemver#semver-expressions-api-ranges) and tell me if that's what you requested?
