### ISSUE TITLE
Implement java.io.Serializable

### ISSUE THREAD

**Issue by mjiderhamn** [zafarkhaja/jsemver#47]
Make `com.github.zafarkhaja.semver.Version` implement `java.io.Serializable`.

For example this makes it easier to persist `com.github.zafarkhaja.semver.Version` using a Hibernate `UserType`.

**Comment by asarkar** [comment]
I don't think this library is maintained any more. I developed https://github.com/asarkar/jsemver, and am curious why can't you simply persist the string representation of the version.

**Comment by zafarkhaja** [comment]
Hello Mattias! Sorry for the delay and thank you for your contribution!
