### ISSUE TITLE
Consider publishing 1.0

### ISSUE THREAD

**Issue by mockitoguy** [zafarkhaja/jsemver#58]
Consider publishing 1.0 version given that this beautiful library is very stable. This would attract more customers and effectively made the world a better place ;)

**Comment by janhoy** [comment]
Have you found an up-to-date fork of this that is published on maven?

**Comment by zafarkhaja** [comment]
Hello Szczepan!

Sorry it took me this long to get back to you. And thank you for caring about jsemver :)

I have been considering it for a very long time really, but unfortunately the API is not stable enough, and some important features are still missing. Hopefully we'll get there after a couple more releases. The first of which I'm releasing in a week.

Cheers,

**Comment by janhoy** [comment]
The solr project migrated over to https://github.com/semver4j/semver4j, so we no longer rely on this.

**Comment by zafarkhaja** [comment]
Hey Jan! That's OK, thank you for letting me know! :)
