### ISSUE TITLE
Get internal version of jsemver itself

### ISSUE THREAD

**Issue by tresf** [zafarkhaja/jsemver#60]
Can you please provide a method to fetch version information (of any sort, `String`, `Version`, etc) from (this) jsemver package?  Some libraries [store this in the `MANIFEST.MF`](https://stackoverflow.com/a/3777116/3196753), others offer [APIs to fetch it](https://github.com/apache/pdfbox/blob/588cb208653262ada43732a4e61c6fa3158f45f4/pdfbox/src/main/java/org/apache/pdfbox/util/Version.java#L46).

At time of writing this, the only way to calculate this information is to parse it from the JAR filename itself, or to obtain the source code and parse it from [`CHANGELOG.md`](https://github.com/zafarkhaja/jsemver/blob/9d28d182cd11dd5476696d3cf70c7fc8b10ffca2/CHANGELOG.md?plain=1#L4) or [`README.md`](https://github.com/zafarkhaja/jsemver/blob/9d28d182cd11dd5476696d3cf70c7fc8b10ffca2/README.md?plain=1#L36)

P.S. Thank you for this wonderful library. :)

**Comment by zafarkhaja** [comment]
Hello Tres! 

Added implementation entries to the MANIFEST
```
Implementation-Title: Java SemVer
Implementation-Version: 0.10.0-SNAPSHOT
```
And there's also a `pom.properties` file with the artifact coordinates
```
artifactId=java-semver
groupId=com.github.zafarkhaja
version=0.10.0-SNAPSHOT
```

Sorry for the delay and thank you for your contribution!
