### ISSUE TITLE
When can we expect a new release?

### ISSUE THREAD

**Issue by decebals** [zafarkhaja/jsemver#63]
I see new commits this year. Do you think you can make a release with what is now in the repository?
I would appreciate it if you could update the changelog file so we know what to expect in the new release.

**Comment by zafarkhaja** [comment]
There are many more changes that I haven't pushed yet. I'll push them within a day or two after I polish a few things and then I'll try to release it next week. Along with the changelog, of course :+1:

**Comment by zafarkhaja** [comment]
Obviously nothing went as planned, but now we are back on track. Pushed all the code changes. The changelog will be arriving later. The ETA for the release is January 10th.

**Comment by zafarkhaja** [comment]
[Released!](https://github.com/zafarkhaja/jsemver/releases/tag/v0.10.0)
