### ISSUE TITLE
When the stable release of the library is expected

### ISSUE THREAD

**Issue by boyan-velinov** [zafarkhaja/jsemver#64]
Hello,

When you plan to release a stable version 1.0.0 of the library?
I can see that it is already well adopted and beleive it is stable indeed :)

Best Regards,
Boayn

**Comment by zafarkhaja** [comment]
Hello Boyan,

It's really hard to tell when exactly, but I promise it's one of my new year's resolutions for 2024 :)

All I can tell you now with more certainty is that most likely I'll be releasing one more version after 0.10.0 before API and the overall code base are stable enough for the 1.0.0 release. In 0.10.0 I focused mainly on refactoring the `Version` class and polishing its API, and in the next 0.11.0 release I'll be focusing on the parsers and range expressions.

**Comment by boyan-velinov** [comment]
Thanks! Good luck in the new year :)
