### ISSUE TITLE
Version#toBuilder should not bomb out when preReleaseVersion is absent

### ISSUE THREAD

**Issue by q3769** [zafarkhaja/jsemver#68]
in v0.10.0, the Version#toBuilder method throws exception if the current Verson instance has no preReleaseVersion: 

https://github.com/zafarkhaja/jsemver/blob/da52637dcda989536d9cac0b3c812f3a524145c3/src/main/java/com/github/zafarkhaja/semver/Version.java#L1274

that doesn't seem reasonable. is it intentional?

**Comment by zafarkhaja** [comment]
Definitely not intentional! :) Will roll out the fix within the next 24 hours. Thanks a lot for reporting :+1:

**Comment by zafarkhaja** [comment]
Fixed in [v0.10.2](https://github.com/zafarkhaja/jsemver/releases/tag/v0.10.2).

P.S. Thanks for reporting the bug, appreciate it!
