### ISSUE TITLE
version compare error

### ISSUE THREAD

**Issue by jzyjinziyan** [zafarkhaja/jsemver#72]
hi, i use this library to handle semantic version compare, and i find a bug:

        Version version = Version.parse("1.1.0-a.146");
        System.out.println(version);
        System.out.println(version.satisfies(">1.1.0-a.146"));

when use the satisfies method with the range argument contains > and character , error occur ：

Illegal character near 'a.146'

**Comment by zafarkhaja** [comment]
Hello and thank you for taking the time to contribute.

Unfortunately pre-release versions are not currently supported by Range Expressions.

Similar issues for your reference: #24, #54, #55.

**Comment by jzyjinziyan** [comment]
thanks much for answer, i found a way to use node-semver library in java and it’s looks work normal.
